[package]
name = "mix-alchemy-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "24.0.0"
rocket = "0.4.11"
rocket_sync_db_pools = "0.1.0-rc.4"
serde = "1.0.192"
serde_json = "1.0.108"
